[+] s5ehfr9
one-among-us/data pull request #120
Opened 2023-06-21 15:48 UTC by wloot

晚安, Lucy.

2023-06-21 16:05 UTC, sauricat requested changes
请查收以下修改建议！谢谢！

2023-06-21 16:05 UTC, sauricat commented on people/s5ehfr9/info.yml
> +id: noname
```suggestion
id: s5ehfr9
```

2023-06-21 16:05 UTC, sauricat commented on people/s5ehfr9/page.md
> +2023年6月16日下午，在两年间的数次尝试自杀后，这一次她成功了，带着她的遗憾和才能永远的离开了我们。可能选择离开这个糟糕的世界是她做过唯一自私的事情。
```suggestion
2023年6月16日下午，在两年间的数次尝试后，这一次，她不幸带着她的遗憾和才能永远地离开了我们。可能选择离开这个糟糕的世界是她做过唯一自私的事情。
```
建议不要用「自杀成功」之类的表述，淡化自杀描写。

2023-06-21 16:05 UTC, sauricat commented on people/s5ehfr9/page.md
> +然而就是在所有人眼里看起来都很优秀的她，患上了重度抑郁症，从小压抑在心里的 MtF 想法彻底爆发。
```suggestion
然而就是在所有人眼里看起来都很优秀的她，从小压抑在心里的 MtF 想法彻底爆发，并且患上了重度抑郁症。
```

2023-06-21 16:09 UTC, wloot commented on people/s5ehfr9/page.md
> +然而就是在所有人眼里看起来都很优秀的她，患上了重度抑郁症，从小压抑在心里的 MtF 想法彻底爆发。
谢谢建议, 已做修改.

2023-06-21 16:11 UTC, sauricat approved these changes

2023-06-21 16:12 UTC, merged

2023-06-24 11:58 UTC, DSLapatura commented
你好,请问一下该如何联系到你们

2023-06-24 12:00 UTC, Aquaticat commented
> 你好,请问一下该如何联系到你们

https://github.com/one-among-us/data/pull/120#issuecomment-1605432018

这里列举的这些方式都可以。

2023-06-24 12:01 UTC, DSLapatura commented
> > 你好,请问一下该如何联系到你们
> 
> https://one-among.us/about/
> 
> 这里列举的这些方式都可以。

感谢