[+] Add mone
one-among-us/data pull request #152
Opened 2023-11-30 08:23 UTC by Twinsherry

- Resolve #62

2023-11-30 08:33 UTC, Twinsherry commented
提示：mone的生日可能存疑，其于1月6日在推文中说十天后是她的生日，父亲给她买了面包等；而后续又说2月8号过生日，出现了前后矛盾的情况，本文暂取后者说法。

2023-11-30 12:19 UTC, LS-KR approved these changes

2023-12-01 04:14 UTC, Aquaticat requested changes
不要刻意写长句子。
不要逐字翻译。
中文和英文或数字间要加空格。

2023-12-01 04:14 UTC, Aquaticat commented on people/mone/page.en.md
> +She also plays Minecraft. She built a small villa with a cozy room belongs to herself in game.
She also plays Minecraft. In that game, she built a small villa with a cozy room belonging to herself.

2023-12-03 04:38 UTC, Aquaticat commented
> Have done emendation by refering changing requests.
> 
> _About programme/program Usage: Program now refers to a computer routine more... I think, and programme is widespreadly used in broadcast..._

See https://www.grammarly.com/blog/program-programme/

Programme is British English's preferred spelling.
In Australian and Canadian English, program is the more common spelling

2023-12-03 04:41 UTC, Aquaticat commented
@Twinsherry 中间的怎么没改？
抱歉又过两天才看。

2023-12-03 05:13 UTC, Twinsherry commented
被Hidden了没有看到xd

2023-12-03 05:21 UTC, Twinsherry commented
另外关于拼写问题，我去查阅了那本Editing Candian English 3rd的手册，里面是写的Canadian English确实在电视广播节目领域在用programme，Grammar那个来源我之前查过，有点怀疑结论不同是和口语有关，毕竟加拿大尤其是南部的口语和美式英语比较相近，而书面英语受到了更多英国皇室的影响。

P47: For some terms, Candadians have adpoted both versions with functional differences: a computer *program* but a *programme* of events.

P71: Table 3.10 Misscellaneous
| Merrisam-Webster | **Canadian Oxford** | Concise Oxford |
| --------------------- | --------------------- | ------------------ |
| program [computer] | program [computer] | program [computer] |
| program [events] | programme [events] | programme [events] |

2023-12-03 05:22 UTC, Twinsherry commented
我去改一下Hidden

2023-12-03 05:24 UTC, Aquaticat commented
> 另外关于拼写问题，我去查阅了那本Editing Candian English 3rd的手册，里面是写的Canadian English确实在电视广播节目领域在用programme，Grammar那个来源我之前查过，有点怀疑结论不同是和口语有关，毕竟加拿大尤其是南部的口语和美式英语比较相近，而书面英语受到了更多英国皇室的影响。
> 
> P47: For some terms, Candadians have adpoted both versions with functional differences: a computer _program_ but a _programme_ of events.
> 
> P71: Table 3.10 Misscellaneous
> 
> Merrisam-Webster	**Canadian Oxford**	Concise Oxford
> program [computer]	program [computer]	program [computer]
> program [events]	programme [events]	programme [events]

好

2023-12-03 05:37 UTC, Twinsherry commented on people/mone/page.en.md
> +> Live better, love yourself further.
其实我当时纠结了一下要不要押一下韵脚，现在读的话感觉即使押了的话读起来也没办法出来那种感觉，还是改了吧xd

2023-12-03 05:38 UTC, Twinsherry commented on people/mone/page.en.md
> +> I feel you are so lovely, very beautiful, sensible and tough. It's quite difficult to weather these things.
这个地方我觉得一个小女孩对于家庭的事情，可能没有过多deal with的能力，所以可能用weather the storm更为合适一些，在“承受，经历一段难过的时间”。

2023-12-03 06:01 UTC, Aquaticat commented on people/mone/page.en.md
> +> I feel you are so lovely, very beautiful, sensible and tough. It's quite difficult to weather these things.
deal with 也可以形容承受。
weather the storm 用得太少了，反而不自然。

2023-12-03 06:01 UTC, Aquaticat commented on people/mone/page.en.md
> +> Live better, love yourself further.
嗯。

2023-12-04 10:57 UTC, Aquaticat approved these changes

2023-12-04 11:35 UTC, merged