[+] Add Hangmster
one-among-us/data pull request #153
Opened 2023-12-01 09:52 UTC by Twinsherry

- resolve #85

2023-12-03 04:56 UTC, Aquaticat requested changes

2023-12-03 04:56 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +Hangmster is an ally of us.
Hangmster is an ally.

没必要写 of us

2023-12-03 04:56 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +They often interacted with friends at Twitter/X, and they were a barrel of laughs. They would also give warm hugs when we needed, console us when we were in anxiety, and mourn for our departed friend
They often interacted with friends on Twitter/X, bringing us laughter.
They gave warm hugs when we needed, consoled us when we were anxious, and mourned for our departed friends.

2023-12-03 04:56 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +Although they seldom mentioned what they loved. However, according to their tweets, they would be attracted by cute things such as little cats. They are fond of Hatsune Miku as well. In the Hatsune M
They seldomly mentioned what they loved.
But according to their tweets, they were interested in cute things such as cats.
They were fond of Hatsune Miku as well.
On the Hatsune Miku 15th anniversary, they expressed their happiness by drawing an illustration:

2023-12-03 04:56 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +Hangmster always be troubled by sleeplessness and anxiety. They once said that they actually didn't like their body in reality, and diversified self-personality would make them more comfortable.
Hangmster was often troubled by insomnia and anxiety.
They once said that they actually didn't like their body, and their less traditional self-expression online made them more comfortable.

2023-12-03 04:56 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +Unfortunately, although they always encouraged us to live bravely, but they still chose to leave at the beginng of the year.
Unfortunately, although they always encouraged us to live bravely, they still chose to leave at the beginning of the year.

英文不能用 although 和 but 在一个句子里。

2023-12-03 04:56 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +Rest well, Hangmster. May you can be yourself as you like.
Rest well, Hangmster. May you can be yourself.

没必要写 as you like

2023-12-03 04:56 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +
在文件结尾加一个空行。

2023-12-03 05:45 UTC, Twinsherry commented on people/Hangmster/page.en.md
> +Hangmster is an ally of us.
嘛，一直这么写其实是呼应网站标题来着，强调“我们之中的某位”，不过要修改的话肯定就是 our ally 了，an ally比较奇怪。

2023-12-03 05:55 UTC, Twinsherry commented on people/Hangmster/page.en.md
> +Hangmster always be troubled by sleeplessness and anxiety. They once said that they actually didn't like their body in reality, and diversified self-personality would make them more comfortable.
Anxiety后面需要加disorder嘛，我第一稿的失眠症用的是insomnia的专有词汇，但是后来想想并列情况下是不是统一口语用词比较好。

2023-12-03 05:58 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +Hangmster is an ally of us.
嗯，our ally 更好。不过不用强调这个。

2023-12-03 05:59 UTC, Aquaticat commented on people/Hangmster/page.en.md
> +Hangmster always be troubled by sleeplessness and anxiety. They once said that they actually didn't like their body in reality, and diversified self-personality would make them more comfortable.
不用加 disorder。insomnia 也不算 official，不用在意并列都用口语表达。

2023-12-04 06:43 UTC, Twinsherry commented
已经修改了目前的英文版本，由于目前没有新增内容来源，已加挂标签。

2023-12-04 10:57 UTC, Aquaticat approved these changes

2023-12-05 07:31 UTC, LS-KR approved these changes

2023-12-10 10:49 UTC, merged