[+] Add Proselyte093
one-among-us/data pull request #155
Opened 2023-12-04 17:47 UTC by Twinsherry

- Resolve #146

2023-12-04 17:49 UTC, Aquaticat commented
不要写具体死亡原因

2023-12-04 17:52 UTC, Twinsherry commented
这块我当时想了一下，应该之前的方针的含义是不写很具体的，尤其是部分化学品中毒或者剧烈物理伤害，看看是否合适（？）

2023-12-04 17:58 UTC, Aquaticat requested changes

2023-12-04 17:58 UTC, Aquaticat commented on people/Proselyte093/page.md
> +尽管直到 11 月初，Ta 仍然想着在生日之前把抑郁症治好，彻底成为一个正常人。不幸的是，精神相关症状逐渐超出了 Ta 的控制。在一个傍晚，Ta 服药外出后失温，留在了漫漫长夜之中。
尽管直到 11 月初，Ta 仍然想着在生日之前把抑郁症治好，彻底成为一个正常人。不幸的是，精神相关症状逐渐超出了 Ta 的控制。在一个傍晚，Ta 外出后，留在了漫漫长夜之中。

2023-12-04 17:58 UTC, Aquaticat commented on people/Proselyte093/page.en.md
> +Until early November, they still thought that curing depression before their birthday. Unfortunally, their mental symptoms gradully overflowed. In an evening, they went out after taking medicine, the
Until early November, they still held on to the hope of curing depression before their birthday. Unfortunally, their mental health gradully worsened. In an evening, they went out of their home and assimilated into the night.

2023-12-04 18:01 UTC, Twinsherry commented
刚刚想到了一个改法，“安静地离开”也可以对应出门，看一下现在这个版本合不合适qwq

2023-12-04 18:08 UTC, Twinsherry commented on people/Proselyte093/page.en.md
> +Until early November, they still thought that curing depression before their birthday. Unfortunally, their mental symptoms gradully overflowed. In an evening, they chose to depart silently, and staye
though about

2023-12-04 18:08 UTC, Twinsherry commented on people/Proselyte093/page.en.md
> +Until early November, they still thought that curing depression before their birthday. Unfortunally, their mental symptoms gradully overflowed. In an evening, they chose to depart silently, and staye
可能太晚了糊涂了

2023-12-04 18:09 UTC, Aquaticat commented on people/Proselyte093/page.en.md
> +Until early November, they still thought that curing depression before their birthday. Unfortunally, their mental symptoms gradully overflowed. In an evening, they chose to depart silently, and staye
好好休息

2023-12-05 14:26 UTC, Twinsherry commented
根据其友人与姐姐的回复，增加了新的内容（仅中文）
英文目前暂未更新。

2023-12-05 14:30 UTC, Twinsherry commented
尝试修复了build问题

2023-12-06 08:01 UTC, Twinsherry commented
增加了少量新的内容并调整了表达，已与其亲友再次联系，看是否还需要再次修改中文版本。

2023-12-11 06:14 UTC, hykilpikonna approved these changes

2023-12-18 01:01 UTC, LS-KR requested changes

2023-12-18 01:01 UTC, LS-KR commented on people/Proselyte093/page.zh_hant.md
> +由於長期的家庭暴力，高中時期被過去的朋友傷害，以及上大學後受到的精神霸淩，Proselyte 飽受焦慮和抑鬱的困擾，逐漸感覺到自己失去了存在的意義。
```suggestion
由於長期的家庭暴力，高中時期被曾經的朋友傷害，以及上大學後受到的精神霸淩，Proselyte 飽受焦慮和抑鬱的困擾，逐漸感覺到自己失去了存在的意義。
```

2023-12-18 01:01 UTC, LS-KR commented on people/Proselyte093/page.zh_hant.md
> +不過在很長的一段時間內，Ta 仍然靠著美好的事物在支撐著，包括 Ta 所喜歡的遊戲，可愛的動物，以及絢麗的插畫。在我們的夥伴陷入焦慮之時，Ta 也會毫不吝嗇地給出自己溫柔的抱抱。
```suggestion
不過在很長的一段時間內，Ta 仍然依靠美好的事物在支撐著，包括 Ta 所喜歡的遊戲，可愛的動物，以及絢麗的插畫。在我們的夥伴陷入焦慮之時，Ta 也會毫不吝嗇地給出自己溫柔的抱抱。
```

2023-12-19 07:32 UTC, LS-KR approved these changes

2023-12-31 16:34 UTC, merged