[+] Mizuki Yuuki
one-among-us/data pull request #182
Opened 2024-01-13 19:55 UTC by LS-KR

Source: Email received by info@one-among.us

2024-01-14 04:23 UTC, Twinsherry commented
可以问问Contributor方便留下id吗

2024-01-14 04:25 UTC, Twinsherry commented
此外，关于离世方式，详细到烧炭的话是否还需要修改一下，娜塔莎也是使用相似的离世方式，我们之前是隐藏起来了。

2024-01-14 05:07 UTC, Twinsherry commented
应该还是有一些语法上的小问题，到时候留着Aquaticat一起改吧。

不过有一个小的专有名词问题，就是这个娃如果我没记错的话应该是属于BJD（Ball—jointed Doll），早年间我在贴吧见过Dollfie Dream的人偶，娃聚的含义应该是"带着自家娃娃和同好聚在一起"，这里的娃应该翻译成doll比较合适（后面的baby理论上也可以替换，如果要表达“自家娃”的意思或许可以用daughter，这部分玩偶大多都以女性形象出现），但是doll party可能也不是一个特别好的翻译。

娃圈的专有英语名词除了bjd我就找不到别的了，这个东西几乎都在东亚发展。

2024-01-14 08:30 UTC, Twinsherry commented on people/Mizuki_Yuuki/page.md
> +也许是财政问题压垮了ta，也许是ta所有的心愿都已完成，
也许是经济问题压垮了ta，也许是ta所有的心愿都已完成，

2024-01-14 08:33 UTC, Twinsherry commented on people/Mizuki_Yuuki/page.md
> +据ta更加亲密的朋友所说，ta已经有两次自杀的尝试了，虽然都被劝下来了，但是第三次执行在定时消息发出之前，很遗憾没有任何人得知。在我得到确切消息时，已经是第二天中午——ta在 2024 年 1 月 10 日在独居小屋里烧炭，永远的离开了我们。
据 ta 更加亲密的朋友所说，ta 已经有两次自杀的尝试了，虽然都被劝下来了，但是第三次执行在定时消息发出之前，很遗憾没有任何人得知。当我得到确切消息时，已经是第二天中午——ta 于 2024 年 1 月 10 日在独居小屋中因窒息而永远地离开了我们。

2024-01-14 08:35 UTC, Twinsherry commented
繁体我就不校对了，有的可能会改成不是那么正确的。
另外私以为照片的顺序可以换一下，感觉第二张拍的角度更有气质x

2024-01-14 19:03 UTC, hykilpikonna commented
重新翻译了英文

2024-01-16 17:07 UTC, Twinsherry requested changes
根據ta更加親密的朋友所說, ta已經有過兩次自殺的嘗試了, 儘管都已經被勸下來; 但是第三次執行在定時消息發出之前, 並沒有任何人得知消息. 在我得知確定的消息時, 已經是第二天的中午——ta於 2024 年 1 月 10 日在獨居小屋內因一氧化碳中毒永遠的離開了我們.

2024-01-16 17:07 UTC, Twinsherry commented on people/Mizuki_Yuuki/page.md
> +<PhotoScroll photos={[ '${path}/photos/photo1.jpg', '${path}/photos/photo2.jpg', ]}/>
---
name: Mizuki Yuuki
info: 
    alias: 瑞希, Mizuki
    location: 上海
---

## 简介

mizuki 生前是一位非常开朗、非常乐观、非常在意朋友的 non-binary，ta 并没有进行 HRT，也没有明确的性别认同。

在大学毕业后，ta 在某家电商公司工作，在上海 2022 年疫情后被裁员，与家里关系不好，只能艰难自立地生活。

我和 ta 结识于国庆假期中的某次聚餐，同样作为 kigurumi 爱好者，我和 ta 还有其他朋友一起参与了上海万圣节、上海 - 沙特文化交流、几次私房拍摄、几次约拍等等，留下了绚烂的回忆。

在照片拍下的那一刻，这张照片已经不仅仅属于摄影了，我的心里只有无尽的悼念和哀思。

在 12 月上旬拿到自己的第一颗 kigurumi 头壳的时候，ta非常地快乐与自由，我在第三天就约 ta 到世纪公园拍摄了一套对我来说第一次外景照片。

在这次拍摄后，ta 组织了一场娃聚，少见地进行了两趟旅行，一趟在圣诞节前去了吉隆坡，一趟在元旦后去了香港。

也许是经济问题压垮了ta，也许是 ta 所有的心愿都已完成，

据 ta 更加亲密的朋友所说，ta 已经有两次自杀的尝试了，虽然都被劝下来了，但是第三次执行在定时消息发出之前，很遗憾没有任何人得知。在我得到确切消息时，已经是第二天中午——ta 于 2024 年 1 月 10 日在独居小屋因一氧化碳中毒永远地离开了我们。

我很遗憾没有多为 ta 拍几次娃片，难以忘怀 ta 的笑容和真挚的友谊。

希望你去往没有痛苦的世界，希望你的未来缤纷多彩。

<PhotoScroll photos={[ '${path}/photos/photo1.jpg', '${path}/photos/photo2.jpg', ]}/>

2024-01-16 17:07 UTC, Twinsherry commented on people/Mizuki_Yuuki/page.zh_hant.md
> +根據ta更加親密的朋友所說, ta已經有過兩次自殺的嘗試了, 儘管都已經被勸下來; 但是第三次執行在定時消息發出之前, 並沒有任何人得知消息. 在我得知確定的消息時, 已經是第二天的中午——ta於 2024 年 1 月 10 日在獨居小屋內因一氧化碳中毒永遠的離開了我們.
根據 ta 更加親密的朋友所說, ta 已經有過兩次自殺的嘗試了, 儘管都已經被勸下來; 但是第三次執行在定時消息發出之前, 並沒有任何人得知消息. 在我得知確定的消息時, 已經是第二天的中午——ta 於 2024 年 1 月 10 日在獨居小屋內因一氧化碳中毒永遠地離開了我們.

2024-01-16 17:07 UTC, Twinsherry commented on people/Mizuki_Yuuki/page.zh_hant.md
> +在這次拍攝後, ta組織了一場娃聚, 少有的進行了兩次旅遊. 一次在聖誕節前去了吉隆坡, 另一次在新曆春節後去了香港.
在這次拍攝後, ta 組織了一場娃聚, 少有地進行了兩次旅遊. 一次在聖誕節前去了吉隆坡, 另一次在新曆春節後去了香港.

2024-01-16 17:07 UTC, Twinsherry commented on people/Mizuki_Yuuki/page.zh_hant.md
> +在 12 月上旬拿到自己的第一個 kigurumi 的頭套的時候, ta非常的快樂和自由. 我在第三天就和ta約定到世紀公園拍攝了一套對我來說的第一次外景相片.
在 12 月上旬拿到自己的第一個 kigurumi 的頭套的時候, ta 非常地快樂和自由. 我在第三天就和 ta 約定到世紀公園拍攝了一套對我來說的第一次外景相片.

2024-01-17 17:13 UTC, Twinsherry approved these changes

2024-01-21 15:30 UTC, merged