[+] Add interrgned
one-among-us/data pull request #196
Opened 2024-02-28 15:03 UTC by Twinsherry

2024-02-28 15:04 UTC, Twinsherry commented
这只是一个初稿，风格可能和站内条目差异比较大。
但是修改之后似乎能看了，所以先发上来。

2024-03-05 02:12 UTC, Aquaticat requested changes
改了一下英文标题。可以先 merge 了我再翻译，要不我不一定什么时候能做。

2024-03-05 02:12 UTC, Aquaticat commented on people/interrgned/page.en.md
> +## You can finish something once again, but You only live once
## You can do lots of things as many times as you want, but you only live once.

如果是完整的句子可以不用 title case

2024-03-05 02:12 UTC, Aquaticat commented on people/interrgned/page.en.md
> +## Afterword
## Afterwords

2024-03-05 02:12 UTC, Aquaticat commented on people/interrgned/page.en.md
> +## Some thoughts
Some Thoughts

2024-03-05 04:45 UTC, Twinsherry commented
这块我就先不动了，还是草稿状态，等那边写完了我再merge

2024-08-04 15:36 UTC, Twinsherry commented
这条目好像搁置太久了，估计有很多bug，我同步一下……

2024-08-19 00:35 UTC, merged