更新條目：鈴木涼宮
one-among-us/data pull request #50
Opened 2023-01-05 14:20 UTC by catears-as

作為這次事件的一個親歷者，我對此條目進行了補充…
正體中文版本出現的不一樣字元可能是針對台灣地區的本土優化…
如果您認為此條目部分內容需要進行驗證，您可以到我的Telegram帳號進行驗證，我會盡可能服從您的工作（鏈結：t.me/CatEars_as）

2023-01-05 14:36 UTC, nmsl6653 commented
嗯...看起来似乎还可以

2023-01-05 16:59 UTC, sauricat commented
感谢补充！写得非常让人感动！有几个意见：
1. 标点符号统一：中文引号统一用直角引号「」，省略号可以改成中文 6 个点省略号……。抱歉这个本来是我们应该在信息编写规范里面写出来的东西但是我们一直没有撰写这个文件。
2. 根据国际自杀报道准则，建议删除自杀的具体方法（在这里是高坠的细节）。
祝好！

2023-01-05 17:35 UTC, hykilpikonna requested changes

2023-01-05 17:35 UTC, catears-as commented
> 感谢补充！写得非常让人感动！有几个意见：
> 1. 标点符号统一：中文引号统一用直角引号「」，省略号可以改成中文 6 个点省略号……。抱歉这个本来是我们应该在信息编写规范里面写出来的东西但是我们一直没有撰写这个文件。
> 2. 根据国际自杀报道准则，建议删除自杀的具体方法（在这里是高坠的细节）。
> 
> 祝好！
好的,我会尽快进行修改哦...

2023-01-05 17:36 UTC, catears-as commented
> 感谢补充！写得非常让人感动！有几个意见：
> 1. 标点符号统一：中文引号统一用直角引号「」，省略号可以改成中文 6 个点省略号……。抱歉这个本来是我们应该在信息编写规范里面写出来的东西但是我们一直没有撰写这个文件。
> 2. 根据国际自杀报道准则，建议删除自杀的具体方法（在这里是高坠的细节）。
> 
> 祝好！

感謝您為我提出的建議，我會盡快修正錯誤。謝謝您喔

2023-01-05 17:42 UTC, catears-as commented on people/suzuki/info.yml
> +died: '2022-12-14'
我會盡量嘗試進行修改，因為我對這並不是太熟練...希望您可以理解喔

2023-01-05 17:44 UTC, hykilpikonna commented on people/suzuki/info.yml
> +died: '2022-12-14'
没关系，谢谢你

2023-01-05 18:14 UTC, sauricat commented
关于 profile picture：我们现在用的这张是因为考虑到不想和 [Ani](https://www.one-among.us/profile/Anilovr) 的重复所以用了铃木的 tg 头像，不知道合不合适，看到你改了一下。

2023-01-05 18:20 UTC, catears-as commented
> 关于 profile picture：我们现在用的这张是因为考虑到不想和 [Ani](https://www.one-among.us/profile/Anilovr) 的重复所以用了铃木的 tg 头像，不知道合不合适，看到你改了一下。

對不起給您造成了麻煩，但是因為考慮到她基本不使用tg...

這個主要看你們的決定吧...如果你們願意更改的話,我會把頭像重新更改的。

2023-01-06 02:14 UTC, merged

2023-01-06 02:21 UTC, sauricat commented
抱歉刚刚合并 PR 的时候因为我不太会用 GitHub 所以产生了一些小的事故。实际上我是想要保留原来的 profile photo，参见 [这条 commit](https://github.com/one-among-us/data/commit/c62f3a88f8954ebacf6ce6dc88f3bed5c8d595a6)。

2023-01-06 02:21 UTC, sauricat commented
现在问题已经解决啦，不用担心~

2023-01-06 03:51 UTC, catears-as commented
> 现在问题已经解决啦，不用担心~

感謝您合併了這個請求，你們的工作是令人驚嘆的！繼續加油喔

2023-01-06 04:20 UTC, catears-as commented
> 抱歉刚刚合并 PR 的时候因为我不太会用 GitHub 所以产生了一些小的事故。实际上我是想要保留原来的 profile photo，参见 [这条 commit](https://github.com/one-among-us/data/commit/c62f3a88f8954ebacf6ce6dc88f3bed5c8d595a6)。

沒有關係的啦，反正還是徵求你們的意見...不論如何都要感謝你們喔！